databases:
  - name: personalWebsiteDbProd
    databaseName: personal_website
    user: personal_website
    plan: starter
    region: Singapore

services:
  - type: web
    name: personalWebsiteWagtailProd
    runtime: python
    buildCommand: "./scripts/build.sh"
    startCommand: "gunicorn src.wsgi:application"
    plan: starter
    region: Singapore
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: personalWebsiteDbProd
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_ADMIN_URL
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: src.settings.production
      - fromGroup: PersonalWebsite
  - type: web
    name: personalWebsiteNextjsProd
    runtime: node
    buildCommand: npm install; npm run build
    startCommand: npm run start
    plan: starter
    region: Singapore
    envVars:
      - fromGroup: PersonalWebsite