# Generated by Django 4.2.8 on 2023-12-27 08:29

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="hero_bullet_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="projectpage",
            name="hero_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "process",
                        wagtail.blocks.StreamBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                (
                                    "paragraph",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    blank=True, required=False
                                                ),
                                            ),
                                            ("paragraph", wagtail.blocks.TextBlock()),
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    blank=True, required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                            ]
                        ),
                    ),
                    (
                        "figma",
                        wagtail.blocks.StructBlock(
                            [("url", wagtail.blocks.CharBlock())]
                        ),
                    ),
                    (
                        "github",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("repo", wagtail.blocks.CharBlock()),
                                ("owner", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.CreateModel(
            name="HeroBullets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("value", models.CharField(blank=True, max_length=255)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projectpage_hero_bullet",
                        to="projects.projectpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
