# Generated by Django 4.2.8 on 2024-01-01 09:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import src.apps.projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_customimage_customrendition"),
        (
            "projects",
            "0002_projectpage_hero_bullet_title_projectpage_hero_title_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="list_view_image",
            field=models.ForeignKey(
                help_text="The image that shows on the projects page",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_list_view_image",
                to="common.customimage",
            ),
        ),
        migrations.AddField(
            model_name="projectpage",
            name="list_view_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projectpage",
            name="year",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2018),
                    src.apps.projects.models.max_value_current_year,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="hero_description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="projectpage",
            name="hero_title",
            field=models.CharField(max_length=255),
        ),
    ]
