# Generated by Django 4.2.8 on 2024-01-08 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_customimage_customrendition"),
        ("projects", "0003_projectpage_list_view_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpage",
            name="mobile_list_view_image",
            field=models.ForeignKey(
                help_text="The image that shows on the projects page for the mobile",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_mobile_list_view_image",
                to="common.customimage",
            ),
        ),
    ]
