# Generated by Django 4.2.8 on 2023-12-17 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_homepage_description_homepage_greating_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="greating",
            new_name="greeting",
        ),
    ]
