# Generated by Django 4.2.8 on 2023-12-24 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_customimage_customrendition"),
        ("home", "0004_rename_greating_homepage_greeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="The image shown on the home page",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_page_image",
                to="common.customimage",
            ),
        ),
    ]
