# Generated by Django 4.2.8 on 2024-01-13 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about_me", "0002_achievement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="achievement",
            old_name="value",
            new_name="achievement",
        ),
    ]
