# Generated by Django 4.2.8 on 2024-01-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about_me", "0003_rename_value_achievement_achievement"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutmepage",
            name="resume_download_url",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
