# Generated by Django 4.2.8 on 2024-07-17 06:20

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_customimage_customrendition"),
        ("about_me", "0004_aboutmepage_resume_download_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("label", models.TextField()),
                ("link", models.URLField(verbose_name="ExternalProjectLink")),
                (
                    "image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aboutmepage_job_role_external_project_image",
                        to="common.customimage",
                    ),
                ),
                (
                    "role",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aboutmepage_job_role_external_project",
                        to="about_me.role",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
