# Generated by Django 4.2.8 on 2023-12-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("url", models.URLField(verbose_name="Link")),
                (
                    "icon_slug",
                    models.CharField(
                        choices=[
                            ("GITHUB", "Github"),
                            ("LINKEDIN", "LinkedIn"),
                            ("INSTAGRAM", "Instagram"),
                        ],
                        db_index=True,
                        default="GITHUB",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Link",
                "verbose_name_plural": "Links",
            },
        ),
    ]
